### ISSUE TITLE
Launchdarkly panics when using actix-web

### ISSUE THREAD

**Issue by claytonSmiley** [launchdarkly/hello-rust#3]
```toml
[dependencies]
launchdarkly-server-sdk = { version = "1.0.0-beta.1" }
env_logger = "0.9.0"
minreq = { version = "2.6.0", features = ["punycode", "https"] }
log = "0.4.17"
actix-rt = "1.1.1"
actix-web = { version = "3.0.0-alpha.2", features=["rustls"] }
actix-web-codegen = "0.4.0"
tokio = { version = "1.15.0", features = ["rt", "macros"] }
```

main.rs
```rust
#[actix_web::main]
async fn main() -> std::io::Result<()> {
    env_logger::init();

    // If Gcloud wants to supply a specific port to this application, let them,
    // otherwise default to 8080
    let port= match std::env::var("PORT"){
        Ok(port) => port,
        _ => String::from("8080")
    };

    let address = format!("0.0.0.0:{}", port);

    HttpServer::new( || {
        App::new()
            .route("/", web::get().to( || async { format!("Hello World! Welcome to the root of this site") }))
            .route("/hello", web::get().to( || async { format!("Hello World! Welcome to my site") }))
            .service(feature)
            .service(listObjects)
            .service(getObjectMetadata)
    })
        .bind(address.clone())?
        .run()
        .await

}


#[get("/feature")]
async fn feature() -> impl Responder {

    // // let sdk_key = std::env::var("SDK_KEY").expect("SDK_KEY env not set");
    // // let feature_flag_key = std::env::var("FEATURE_FLAG_KEY").expect("FEATURE_FLAG_KEY env not set");
    let config: Config = ConfigBuilder::new("PURPOSELY OBFUSCATED SDK KEY").build();
    let client: Client = Client::build(config).expect("Client failed to build");

    client.start_with_default_executor();
    if !client.initialized_async().await {
        panic!("SDK failed to initialize");
    }

    let user = User::with_key("color").name("USERNAME").build();
    let result = client.bool_variation(&user, "color", false);
    let world_color = client.str_variation(&user, "color", "BLACK".parse().unwrap());
    let country_user = User::with_key("country").name("USERNAME").build();
    let country_flag_result = client.bool_variation(&country_user, "country", false);
    let country = client.str_variation(&country_user, "country", "AUSTRALIA".parse().unwrap());

    println!(
        "Feature flag 'color' is {} for this user, showing {} world",
        result, world_color
    );
    println!(
        "Feature flag 'country' is {} for this user, showing {} country",
        country_flag_result, country
    );
    client.close();
    format!("your world is {}, and your Country is {}", world_color, country)

}
```

Error when navigating to "/feature" path in browser:
```
     Running `target\debug\rust-sample-repo.exe`
thread 'actix-rt:worker:0' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime', C:\Users\MY USERNAME\.cargo\registry\src\github.com-1ecc6299db9ec823\launchdarkly-server-sdk-1.0.0-beta.3\src\data_source.rs:138:9
```
